# Generated by Django 4.0 on 2021-12-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('logo', models.URLField()),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('market_cap', models.FloatField(max_length=200)),
            ],
        ),
    ]
